"""Small, explicit high-confidence username review policy.

Ordinary profanity is intentionally not represented here. These terms are
only used to send an application to human review; they never cause rejection.
"""

BLOCKED_BIGOTRY_TERMS = (
    {"value": "beaner", "category": "anti-latino", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "cameljockey", "category": "anti-arab-muslim", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "chink", "category": "anti-asian", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "chinaman", "category": "anti-asian", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "coon", "category": "anti-black", "match_mode": "component",
     "collision_prefixes": ("raccoon",)},
    {"value": "currymuncher", "category": "anti-south-asian", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "darkie", "category": "anti-black", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "dothead", "category": "anti-south-asian", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "dyke", "category": "homophobic", "match_mode": "component",
     "collision_prefixes": ("vandyke",)},
    {"value": "fag", "category": "homophobic", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "faggot", "category": "homophobic", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "gook", "category": "anti-asian", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "gyppo", "category": "anti-roma", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "heeb", "category": "antisemitic", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "injun", "category": "anti-indigenous", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "jigaboo", "category": "anti-black", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "kike", "category": "antisemitic", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "lesbo", "category": "homophobic", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "mongoloid", "category": "ableist", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "muzzie", "category": "anti-arab-muslim", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "nigger", "category": "anti-black", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "paki", "category": "anti-south-asian", "match_mode": "component",
     "collision_prefixes": ("pakistan", "pakistani")},
    {"value": "pickaninny", "category": "anti-black", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "polack", "category": "anti-polish", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "porchmonkey", "category": "anti-black", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "raghead", "category": "anti-arab-muslim", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "retard", "category": "ableist", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "sambo", "category": "anti-black", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "sandnigger", "category": "anti-arab-muslim", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "sheeny", "category": "antisemitic", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "shemale", "category": "transphobic", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "slanteye", "category": "anti-asian", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "spaz", "category": "ableist", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "spic", "category": "anti-latino", "match_mode": "component",
     "collision_prefixes": ("spice", "spicy")},
    {"value": "squaw", "category": "anti-indigenous", "match_mode": "component",
     "collision_prefixes": ()},
    {"value": "towelhead", "category": "anti-arab-muslim", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "trannie", "category": "transphobic", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "tranny", "category": "transphobic", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "wagonburner", "category": "anti-indigenous", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "wetback", "category": "anti-latino", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "windowlicker", "category": "ableist", "match_mode": "substring", "allow_fuzzy": True},
    {"value": "zipperhead", "category": "anti-asian", "match_mode": "substring", "allow_fuzzy": True},
)
