# Generated by Django 6.0.8 on 2026-08-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=64)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('conference', models.CharField(max_length=60)),
                ('division', models.CharField(max_length=50)),
                ('use_for_ballot', models.BooleanField()),
                ('short_name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.CharField(max_length=40)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('publish_date', models.DateTimeField()),
                ('ap_date', models.DateTimeField()),
                ('last_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.poll')),
            ],
            options={
                'ordering': ('publish_date',),
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('poll_type', models.IntegerField(blank=True, choices=[(1, 'Human'), (2, 'Computer'), (3, 'Hybrid')], null=True)),
                ('user_type', models.IntegerField(choices=[(1, 'Voter'), (2, 'Provisional Voter')])),
                ('overall_rationale', models.TextField(blank=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_calculated', models.DateTimeField()),
                ('human', models.BooleanField(default=True)),
                ('computer', models.BooleanField(default=True)),
                ('hybrid', models.BooleanField(default=True)),
                ('main', models.BooleanField(default=True)),
                ('provisional', models.BooleanField(default=False)),
                ('before_ap', models.BooleanField(default=True)),
                ('after_ap', models.BooleanField(default=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('first_place_votes', models.IntegerField()),
                ('points', models.IntegerField()),
                ('points_per_voter', models.FloatField()),
                ('std_dev', models.FloatField()),
                ('votes', models.IntegerField()),
                ('result_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.resultset')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.team')),
            ],
        ),
        migrations.CreateModel(
            name='BallotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('rationale', models.TextField(blank=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.ballot')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.team')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('primary_affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.team')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionalUserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Accepted'), (3, 'Rejected')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.user')),
            ],
        ),
        migrations.AddField(
            model_name='ballot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.user'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Voter'), (2, 'Provisional Voter')])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSecondaryAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['close_date'], name='poll_poll_close_d_1afe1c_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['publish_date'], name='poll_poll_publish_5d7c96_idx'),
        ),
    ]
